name: 'Deploy app to ELB'
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**'
env:
  region: ${{ secrets.AWS_REGION }}
  repository: ${{ secrets.AWS_REPOSITORY }}
  s3Bucket:  ${{ secrets.S3_BUCKET }}
  serviceName: 'moirai-app'
  envName: 'prod'
  appVersion: ${{ github.run_number }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Login to Repository'
        run: |
          aws ecr get-login-password --region ${{ env.region }} | docker login --username AWS --password-stdin ${{ env.repository }}/${{ env.serviceName }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Build Docker image'
        run: |
          docker build -t ${{ env.serviceName }} -f ./Dockerfile .
      - name: 'Push Docker image to repository'
        run: |
          docker tag ${{ env.serviceName }}:latest ${{ env.repository }}/${{ env.serviceName }}:latest
          docker push ${{ env.repository }}/${{ env.serviceName }}:latest
      - name: 'Register a new version'
        run: |
          aws --region ${{ env.region }} elasticbeanstalk create-application-version --application-name ${{ env.serviceName }} --version-label ${{ env.appVersion }} --source-bundle S3Bucket=${{ env.s3Bucket }},S3Key=Dockerrun.aws.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Trigger deployment'
        run: |
          aws --region ${{ env.region }} elasticbeanstalk update-environment --application-name ${{ env.serviceName }} --environment-name ${{ env.envName }} --version-label=$APP_VERSION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
